import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Categories from '../components/Categories';
import PostCard from '../components/PostCard';
import PostWidget from '../components/PostWidget';
import { getPosts } from '../services';
import FeaturedPosts from '../sections/featuredPosts';

// const posts = [
//   { title: 'React Testing', excerpt: 'Learn React Testing' },
//   { title: 'React with tailwind', excerpt: ' Learn react with tailwind' },
// ];

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jovian Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />
      <div className={styles.postContainer}>
        <div>
          {posts.map((post, i) => (
            <PostCard post={post.node} key={post.title} />
          ))}
        </div>
        <div>
          <PostWidget />
          <Categories />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts },
  };
}
